import Layout from '@/components/Layout'
import { APP_URL } from '@/components/SiteChrome'
import { ArrowRight, Check, FileSpreadsheet, FolderLock, Library, QrCode, Search, Users } from 'lucide-react'

const journeys = [
  {icon: FileSpreadsheet, label:'01 / SET UP', title:'Start with what you already have', copy:'Import the spreadsheet your librarian already trusts, then enrich each record with files, condition, location and custom fields.', points:['Bulk spreadsheet import','Flexible metadata','Printable labels and cover sheets']},
  {icon: Search, label:'02 / FIND', title:'Answer “do we have it?” in seconds', copy:'Search every title, composer, arranger, genre and custom field from one place—on desktop or from the band room.', points:['Fast whole-library search','Powerful filters','Mobile-friendly records']},
  {icon: Library, label:'03 / MANAGE', title:'Know the state of every set', copy:'See missing parts, loans, condition and physical location before a rehearsal turns into a treasure hunt.', points:['Part completeness','Loan history','Library numbers and barcodes']},
  {icon: Users, label:'04 / SHARE', title:'Give everyone the right access', copy:'Librarians can manage the catalogue while members securely open only the music and libraries they are authorised to use.', points:['Role-based permissions','Organisation separation','Watermarked downloads']},
]

export default function Features(){return <Layout title="Features — Music library software for bands | BandSync" description="Import, search, track and securely share your band's sheet music library from web and mobile.">
  <section className="subpage-hero feature-hero"><div className="shell narrow"><span className="section-number light">BUILT AROUND THE LIBRARIAN&apos;S JOB</span><h1>From filing cabinet<br/>to <em>one source of truth.</em></h1><p>BandSync connects your catalogue, physical sets and authorised digital files—without asking your band to learn a complicated new system.</p><div className="hero-actions centered"><a className="button" href={APP_URL}>Build your free library <ArrowRight/></a><a className="text-link" href="#workflow">Explore the workflow ↓</a></div></div></section>
  <section className="journey-section" id="workflow"><div className="shell journey-list">{journeys.map(({icon:Icon,...x},i)=><article className="journey" key={x.title}><div className="journey-copy"><span className="section-number">{x.label}</span><Icon/><h2>{x.title}</h2><p>{x.copy}</p><ul>{x.points.map(p=><li key={p}><Check/>{p}</li>)}</ul></div><div className={`journey-visual visual-${i}`}><div className="visual-window"><div className="visual-top"><span/><span/><span/></div>{i===0&&<><div className="import-drop"><FileSpreadsheet/><b>library-catalogue.xlsx</b><small>1,842 rows ready to import</small></div><div className="progress"><i/></div></>}{i===1&&<><div className="big-search"><Search/>Floral Dance</div><div className="result-line"><b>The Floral Dance</b><span>Complete · Bay 4</span></div><div className="result-line"><b>Floral Fantasia</b><span>Missing 1 part</span></div></>}{i===2&&<><div className="status-grid"><span><b>94%</b> complete</span><span><b>12</b> on loan</span></div><div className="barcode"><QrCode/><b>BSL-01842</b></div></>}{i===3&&<><div className="access-row"><Users/><b>Band members</b><span>View</span></div><div className="access-row"><FolderLock/><b>Librarians</b><span>Manage</span></div><div className="access-row"><Users/><b>Guests</b><span>Off</span></div></>}</div></div></article>)}</div></section>
  <section className="security-section"><div className="shell security-grid"><div><span className="section-number light">BUILT FOR REAL COLLECTIONS</span><h2>Useful on day one.<br/><em>Dependable every week.</em></h2></div><div className="security-copy"><p>Use BandSync in the browser, on iPhone and iPad, with Android currently in closed testing. Your organisation&apos;s access stays separated and your catalogue can be exported.</p><div className="security-points"><span><FolderLock/> Private libraries</span><span><Users/> Member permissions</span><span><QrCode/> Scan from the shelf</span></div></div></div></section>
  <section className="final-cta"><div className="cta-lines"/><div className="shell"><span className="eyebrow"><span className="live-dot"/> Import from Excel</span><h2>Your catalogue already exists.<br/>Make it work harder.</h2><p>Start free with up to 500 pieces and no credit card.</p><a className="button button-large" href={APP_URL}>Build your free library <ArrowRight/></a></div></section>
 </Layout>}
